[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
 
[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888